---
title: "ggplot"
author: "QiLu"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)

```
## create the weather data

```{r, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```


## create a ggplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```



```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```


```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth( se = FALSE) + 
  facet_grid(. ~ name)
```


```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .35) +
  geom_smooth(se = FALSE)
```

2d density
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_bin2d()
```

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(~name)
```

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4)
```

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```


```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```


riage plots
```{r}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)
```


save a plot
```{r}
weather_plot =
  ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)

ggsave("weather_plot.pdf", weather_plot)

```

```{r, fig.width=2}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(scale = .85)
```






## lesson 2
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )
```

x aixs tick 
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") +
  scale_x_continuous(
    breaks = c(-15, -5, 20),
    labels = c("-15ยบ C", "0", "15"))
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") + 
  scale_color_hue(name = "Location", h = c(100, 300))
```
```{r}
ggp_temp_plot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

ggp_temp_plot
```

themns
```{r}
ggp_temp_plot +
  theme_minimal() + 
  theme(legend.position = "bottom") #order matters!!!

```
##more than one dataset
```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park)
```

#change color of points
```{r}
waikiki %>%
  ggplot(aes(x = date, y = tmax)) +
  geom_point(alpha= 0.5, color = "blue")
```


## multi-panel plots
```{r}
ggp_scatter = 
  weather_df%>%
  ggplot(aes(x = date, y = tmax)) +
  geom_point()

ggp_density = 
  weather_df%>%
  ggplot(aes(x = precip, fill= name)) +
  geom_density()

ggp_box = 
  weather_df%>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

ggp_temp_plot + 
```

